### ISSUE TITLE
Mentors Required for Node School Event Bengaluru

### ISSUE THREAD

**Issue by somsharan** [nodeschool/bangalore#4]
If any one interested to be as the Mentor for this event are Requested to comment below with the contact info of yours

**Comment by geekgugi** [comment]
I will be very much interested.

**Comment by anmolview** [comment]
yes i am interested

**Comment by somsharan** [comment]
Sorry for now the event got finished, u can follow us on twitter and meetup.com for future events updates and can be mentor for those events. Thank you for interest.

**Comment by jigarjain** [comment]
I can be available for mentoring the new comers to Nodejs & Express :) Let me know how can I help you guys.

**Comment by abyv** [comment]
Ive given you the contact details via meetup.. c u :)

**Comment by vishnumishra** [comment]
Hey I'm interested.

**Comment by abhihebbar** [comment]
Interested.

**Comment by Harsha509** [comment]
Interested

**Comment by tarungarg546** [comment]
Interested

**Comment by sumantro93** [comment]
Interested :)

**Comment by narengs7** [comment]
Interested :)

**Comment by narengs7** [comment]
Hi, I'm Also Interested :+1:

**Comment by tarungarg546** [comment]
Hey lets plan something interesting for International nodeschool day rather than wasting our time there in installing nodeschool packages.

**Comment by somsharan** [comment]
It would, we will be interacting with other nodeschool event which are organizing on the same day withing the same time duration.

**Comment by sunnykgupta** [comment]
Hi. Interested.

**Comment by narengs7** [comment]
Issue seems to be closed.. o.O..
But suddenly can i know for which..... u are saying...

**Comment by somsharan** [comment]
Thank you for your interest, will be announcing next event very soon, u can join us on  `https://www.meetup.com/Bengaluru-Nodeschool-Event/` to get updates regarding the event.
