### ISSUE TITLE
virtual hosting in node.js

### ISSUE THREAD

**Issue by JyotiDuhan** [nodeschool/bangalore#5]
Hi,
I am using express on node.js.
I tried to assign a host name to my local site http://localhost:3001 as local.com.
 A more reference to the issue is here : 
http://stackoverflow.com/questions/30409528/issue-while-setting-virtual-host-with-node-js-on-express

Can anyone help me with a way to virtually host my site(built on express) in node.js?

**Comment by somsharan** [comment]
Hi,

Check the following link it might help http://www.hacksparrow.com/vhost-in-express-js.html 
if not let me known.

**Comment by JyotiDuhan** [comment]
Hi,
The link you have given is for older versions of express. I tried it but its loading the vhost_example index page for both http://apple.localhost and  http://book.localhost.
My node version is : v0.12.3 Express version : 4.12.4 NPM version : 2.9.1

The app.js of vhost_example  is : 

var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var evh = require('express-vhost');
var http = require('http');

var routes = require('./routes/index');
var users = require('./routes/users');

var app = express();

// vhost apps
var apple_localhost = require('./websites/apple.localhost');
var book_localhost = require('./websites/book.localhost');

  app.set('port', process.env.PORT || 3000);
  app.set('views', __dirname + '/views');
  app.set('view engine', 'jade');
  
  // apply the vhost middleware, before the router middleware
  app.use(evh.vhost('apple.localhost', apple_localhost))
  app.use(evh.vhost('*.localhost', book_localhost));

  
  app.use(express.static(path.join(__dirname, 'public')));

// app.get('/', routes.index);
app.use('/', routes);
http.createServer(app).listen(app.get('port'), function(){
  console.log("vhost enabled Express server listening on port " + app.get('port'));
});


The app.js of apple.localhost is : 

var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');

var routes = require('./routes/index');
var users = require('./routes/users');

var app = express();

app.set('views', __dirname + '/views');
app.set('view engine', 'jade');
app.use(express.static(path.join(__dirname, 'public')));

app.get('/', function(req, res) {
  res.send('APPE');
});

module.exports = app;


The app.js of book.localhost is : 

var express = require('express');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');

var routes = require('./routes/index');
var users = require('./routes/users');

var app = express();


app.set('views', __dirname + '/views');
app.set('view engine', 'jade');
app.use(express.static(path.join(__dirname, 'public')));

app.get('/', function(req, res) {
  res.send('BOOK');
});

module.exports = app;

**Comment by JyotiDuhan** [comment]
Can anyone suggest on this plz?

**Comment by somsharan** [comment]
Hi,

We need to use only vhost as express-vhost is depreciated in express 4.
Below thing works for me in local:

// Module dependencies.
var application_root = __dirname,
    express = require( 'express' ),
    vhost = require( 'vhost' );

function createVirtualHost(domainName, dirPath) {
    return vhost(domainName, express.static( dirPath ));
}

//Create server
var app = express();


//Create the virtual hosts
var potatoHost = createVirtualHost("www.potato.com", "potato"); //potato is application folder 
var tomatoHost = createVirtualHost("www.tomato.com", "tomato");//tomato is application folder 

//Use the virtual hosts
app.use(potatoHost);
app.use(tomatoHost);

//Start server
var port = 3000;
app.listen( port, function() {
    console.log( 'Express server listening on port %d in %s mode', port, app.settings.env );
});

U need to access domain names with port no ex: www.potato.com:3000
for more information check this link http://shamadeh.com/blog/web/nodejs/express/2014/07/20/ExpressMultipleSites.html

**Comment by JyotiDuhan** [comment]
Hi,

I achieved the virtual hosting installing nginx and used below configurations under /etc/nginx/sites-available/ for two different applications local.com and myapp.com:

#for local.com : 

server {
    listen 80;

    server_name local.com;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

}


#for myapp.com : 

server {
    listen 80;

    server_name myapp.com;

    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

}
 
And now if i type local.com or myapp.com in browser, it links me to my dedicated application. :)
